version: "3.8"

services:
  mysqlDb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: foyer
    ports:
      - "3313:3306"
    volumes:
      - db:/var/lib/mysql
    healthcheck:
        test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
        interval: 10s
        timeout: 5s
        retries: 5
    networks:
      mynetwork:
        ipv4_address: 192.168.50.6  # Specify the desired fixed IP address

  app:
    depends_on:
      - mysqlDb
    image: ramibrick/tp-foyer:latest  # Utilisez ici la version spécifique 0.0.1
    restart: on-failure
    ports:
      - "8085:8085"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqlDb:3306/foyer?createDatabaseIfNotExist=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": "",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      mynetwork:
        ipv4_address: 192.168.50.22

volumes:
  db:
networks:
  mynetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.50.0/16